### ISSUE TITLE
Lack critical account management feature.

### ISSUE THREAD

**Issue by SuperCVL** [Tassadraft/Tassadraft-v2#10]
Need change password.
Need change email adress.
Need change username.
![chrome_K2YUN6XH8K](https://github.com/user-attachments/assets/754929da-ee5b-473f-8880-a5a7f4029185)

**Comment by Tassadar921** [comment]
For the moment, present on https://api.tassadraft.com

**Comment by Tassadar921** [comment]
Email won't be editable as it's the only way to check users' identity
